import fs from 'node:fs';
import path from 'node:path';
import { CONTEXT_SNAPSHOT_MAX_BYTES } from '@avorant/shared';
import { buildDigest } from '../engine/digest.js';
import type { Store } from '../db/store.js';

/**
 * context.md — a full-overwrite snapshot (never a log), written at milestones:
 * session start, contract approved, review APPROVE, issue closed, override,
 * session end. Generated from the same buildDigest() as catch_up/join, so
 * there is exactly one digest implementation.
 */
export function writeContextSnapshot(store: Store, sessionId: string, repoPath: string): void {
  if (!fs.existsSync(repoPath)) return; // fixture sessions with fake paths
  const digest = buildDigest(store, sessionId);
  const header =
    '<!-- Generated by Avorant Group Chat at each milestone. This is a STARTUP SNAPSHOT — for live state call the avorant catch_up tool. -->\n\n';
  let body = header + digest + '\n';
  if (Buffer.byteLength(body, 'utf8') > CONTEXT_SNAPSHOT_MAX_BYTES) {
    body = body.slice(0, CONTEXT_SNAPSHOT_MAX_BYTES - 2) + '…\n';
  }
  fs.writeFileSync(path.join(repoPath, 'context.md'), body);
}
